Lesson 9
alecxkelly/IOProgramming-Alecxis pull request #2
Opened 2024-07-23 18:10 UTC by alecxkelly

2024-07-30 02:31 UTC, a-zuniga commented on index.html
>      <h2>Experience</h2>
This should be wrapped in a <section></section> tag just how the about section is laid out!

2024-07-30 02:32 UTC, a-zuniga commented on index.html
>      <h2>Connect</h2>
Should also be wrapped in a ```<section></section>``` tag

2024-07-30 02:34 UTC, a-zuniga requested changes
You're almost there! Just wrap the experience and connect elements with a sections tag and you'll meet all of the assignments requirements! Don't forget about the id as well, you did it correctly for the about section!

2024-08-01 00:44 UTC, merged

2024-08-01 15:20 UTC, TeresaSwarthout commented
Lesson 9 looks good!  Great start on your site.

Few minor comments:
I am a creative Tech/Entrepreneur from Philadelphia, now I am worldwide.   ->  I'm not quite sure what this sentence means - you might expand on it a bit.
Your contact link doesn't work.
You have style comments here, which you will eventually want to put in your index.css
  body {background-color: powderblue;}
        h1 {color: rgb(5, 9, 223);}
        p {color: blue;}